debug: false

logging:
  level:
    root: INFO

server:
  port: 8081
  http2:
    enabled: true
  error:
    whitelabel:
      enabled: false
    include-message: always

spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:h2:file://${DB_PATH:./../testdb}
    repositories:
      enabled: true
    username: sa
    password:
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    post: ${EMAIL_PORT:587}
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

endpoints:
  frontend: ${FRONTEND_BASE_URL:http://localhost:3000}
  rest: ${REST_API_BASE_URL:http://localhost:8080}
  authorizer: ${AUTHORIZER_BASE_URL:http://localhost:8081}

email:
  address: ${EMAIL_ADDRESS}

jwt:
  secret: ${JWT_SECRET:NkK1y4YK8B4X9yiqCdBdm9FJjTyePhhsz6vfPq8npkvh2Zjx}
