debug: true

logging:
  level:
    root: INFO

server:
  port: 8080
  http2:
    enabled: true
  error:
    whitelabel:
      enabled: false
    include-message: always

spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:${POSTGRES_URL:postgresql://postgres:postgres@localhost:5432/postgres}
    repositories:
      enabled: true
  data:
    r2dbc.repositories.enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_URL:159.65.88.244:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "*"

endpoints:
  frontend: ${FRONTEND_BASE_URL:http://localhost:3000}
  rest: ${REST_API_BASE_URL:http://localhost:8080}
  authorizer: ${AUTHORIZER_BASE_URL:http://localhost:8081}

group-dms:
  maxMembers: ${GROUP_DM_MAX_MEMBERS:10}
  maxChannelsPerUser: ${GROUP_DM_MAX_CHANNELS_PER_USER:10}

kafka:
  producer:
    topic: ${KAFKA_PRODUCER_TOPIC:notcord_events}
